pipeline {
   agent {label 'master'}
   environment {
    DOCKERHUB_CREDENTIALS=credentials('dockerhub_cred')
   }
   stages {
        stage('Build Image'){
            steps{
                sh 'ls; docker build -t italianodev/simplewebapp:$BUILD_NUMBER simplewebapp'
            }
        }
        stage('Login Dockerhub'){
            steps{
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Push image'){
            steps{
                sh 'docker push italianodev/simplewebapp:$BUILD_NUMBER'
            }
        }
   }
   post {
    always {
        sh 'docker logout'
    }
   }
}